######################################################################
# Automatically generated by qmake (3.0) Thu Sep 22 10:18:34 2016
######################################################################

QT+=widgets
TEMPLATE = app
TARGET = src
INCLUDEPATH += .

# Input
HEADERS += SceneShader.h Shader.h
SOURCES += main.cpp SceneShader.cpp Shader.cpp
